services:
  user-service:
    container_name: unreal-api
    build:
      context: .
    env_file:
      - .env
    environment:
      WAIT_HOSTS: pg:5432, redis:6379
      PG_HOST: pg
      PG_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ENV: prod
    depends_on:
      - pg
      - redis
    ports:
      - "${PORT}:${PORT}"

  redis:
    image: redis:7.2.4-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - redis-data:/data
    ports:
      - "${REDIS_PORT}:6379"

  pg:
    image: postgres:17-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:5432

volumes:
  redis-data:
    name: unreal-redis-data
  pg-data:
    name: unreal-pg-data
